import { defineDistribution } from "@borg/kernel";

export const desktopDistribution = defineDistribution({
  id: "borg.desktop",
  name: "Borg Desktop",
  version: "0.1.0",
  kernel: "^0.1.0",
  plugins: [
    "borg.a2a",
    "borg.anthropic",
    "borg.azure",
    "borg.bots",
    "borg.channel.discord",
    "borg.channel.google",
    "borg.channel.imap",
    "borg.channel.m365",
    "borg.channel.mock",
    "borg.channel.slack",
    "borg.chat",
    "borg.coinbase",
    "borg.config.sqlite",
    "borg.context-map",
    "borg.copilot",
    "borg.feedback",
    "borg.graphs",
    "borg.hello",
    "borg.mcp",
    "borg.mcp-apps",
    "borg.memory.knowledge",
    "borg.mock-llm",
    "borg.ollama",
    "borg.openai",
    "borg.openrouter",
    "borg.remote",
    "borg.search.brave",
    "borg.search.tavily",
    "borg.secrets.dev",
    "borg.secrets.os",
    "borg.security.prompt-injection",
    "borg.themes",
    "borg.tools.core",
    "borg.tools.echo",
    "borg.usage",
  ],
  defaults: {
    models: ["borg.mock-llm:mock:scripted"],
  },
  policy: {
    detachedResults: [
      { pluginId: "borg.chat", subjectKinds: ["chat-session", "chat-turn"] },
      { pluginId: "borg.bots", subjectKinds: ["bot", "bot-attempt"] },
      { pluginId: "borg.graphs", subjectKinds: ["graph-instance"] },
      { pluginId: "borg.a2a", subjectKinds: ["a2a-task"] },
    ],
  },
});
