// Generated by scripts/generate-bundled-plugins.mjs. Do not edit.
import type { PluginUiDefinition } from "@borg/plugin-sdk";
import type { Component } from "solid-js";

export type UiPluginLoader = () => Promise<{
  readonly default: PluginUiDefinition<Component>;
}>;

export const bundledUiPlugins: Readonly<Record<string, UiPluginLoader>> = {
  "borg.feedback": async () => import("@borg/plugin-feedback/ui"),
  "borg.hello": async () => import("@borg/plugin-hello/ui"),
  "borg.mock-llm": async () => import("@borg/plugin-mock-llm/ui"),
  "borg.secrets.dev": async () => import("@borg/plugin-secrets-dev/ui"),
  "borg.secrets.os": async () => import("@borg/plugin-secrets-os/ui"),
};
