// Generated by scripts/generate-bundled-plugins.mjs. Do not edit.
import type { PluginUiDefinition } from "@borg/plugin-sdk";
import type { Component } from "solid-js";

export type UiPluginLoader = () => Promise<{
  readonly default: PluginUiDefinition<Component>;
}>;

export const bundledUiPlugins: Readonly<Record<string, UiPluginLoader>> = {
  "borg.a2a": async () => import("@borg/plugin-a2a/ui"),
  "borg.anthropic": async () => import("@borg/plugin-anthropic/ui"),
  "borg.bots": async () => import("@borg/plugin-bots/ui"),
  "borg.channel.discord": async () => import("@borg/plugin-channel-discord/ui"),
  "borg.chat": async () => import("@borg/plugin-chat/ui"),
  "borg.feedback": async () => import("@borg/plugin-feedback/ui"),
  "borg.graphs": async () => import("@borg/plugin-graphs/ui"),
  "borg.hello": async () => import("@borg/plugin-hello/ui"),
  "borg.mcp": async () => import("@borg/plugin-mcp/ui"),
  "borg.mcp-apps": async () => import("@borg/plugin-mcp-apps/ui"),
  "borg.mock-llm": async () => import("@borg/plugin-mock-llm/ui"),
  "borg.openai": async () => import("@borg/plugin-openai/ui"),
  "borg.search.brave": async () => import("@borg/plugin-search-brave/ui"),
  "borg.search.tavily": async () => import("@borg/plugin-search-tavily/ui"),
  "borg.secrets.dev": async () => import("@borg/plugin-secrets-dev/ui"),
  "borg.secrets.os": async () => import("@borg/plugin-secrets-os/ui"),
  "borg.themes": async () => import("@borg/plugin-themes/ui"),
  "borg.usage": async () => import("@borg/plugin-usage/ui"),
};
