// Generated by scripts/generate-bundled-plugins.mjs. Do not edit.
import type { PluginSource } from "@borg/kernel";
import type { PluginDefinition } from "@borg/plugin-sdk";

export const bundledMainPlugins: readonly PluginSource[] = [
  {
    manifest: {
      "id": "borg.a2a",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-a2a/main",
      "ui": "@borg/plugin-a2a/ui",
      "permissions": [
        "loops.start",
        "personas.read",
        "tools.invoke",
        "ui.flightDeck",
        "ui.settings",
        "workspace.manage"
      ],
      "contributes": {
        "commands": [
          "borg.a2a.getStatus"
        ],
        "kinds": [
          "flightDeckWidget",
          "settingsPage"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-a2a/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.anthropic",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-anthropic/main",
      "ui": "@borg/plugin-anthropic/ui",
      "permissions": [
        "models.register",
        "network:api.anthropic.com",
        "secrets:read",
        "secrets:write",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "commands": [
          "borg.anthropic.connect",
          "borg.anthropic.disconnect",
          "borg.anthropic.getStatus"
        ],
        "kinds": [
          "llmProvider",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-anthropic/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.azure",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-azure/main",
      "ui": "@borg/plugin-azure/ui",
      "permissions": [
        "models.register",
        "network:dynamic",
        "secrets:read",
        "secrets:write",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "commands": [
          "borg.azure.connect",
          "borg.azure.disconnect",
          "borg.azure.getStatus"
        ],
        "kinds": [
          "llmProvider",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-azure/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.bots",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-bots/main",
      "ui": "@borg/plugin-bots/ui",
      "permissions": [
        "executions.manage",
        "loops.start",
        "personas.read",
        "tools.invoke",
        "tools.register",
        "ui.flightDeck",
        "ui.workspace",
        "workspace.manage"
      ],
      "contributes": {
        "commands": [
          "borg.bots.create",
          "borg.bots.delete",
          "borg.bots.get",
          "borg.bots.list",
          "borg.bots.listLogs",
          "borg.bots.start",
          "borg.bots.stop"
        ],
        "events": [
          "borg.bots.completed",
          "borg.bots.failed",
          "borg.bots.started",
          "borg.bots.stopped",
          "borg.bots.updated"
        ],
        "kinds": [
          "flightDeckWidget",
          "tool",
          "workspaceView"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-bots/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.channel.discord",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-channel-discord/main",
      "ui": "@borg/plugin-channel-discord/ui",
      "permissions": [
        "channels.register",
        "network:dynamic",
        "network:websocket",
        "runtime.background",
        "secrets:read",
        "secrets:write",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.channel.discord.disconnect",
          "borg.channel.discord.getStatus",
          "borg.channel.discord.verify"
        ],
        "kinds": [
          "channel",
          "settingsPage"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-channel-discord/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.channel.google",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-channel-google/main",
      "ui": "@borg/plugin-channel-google/ui",
      "permissions": [
        "channels.register",
        "oauth.connect",
        "network:dynamic",
        "runtime.background",
        "tools.register",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.channel.google.connect",
          "borg.channel.google.disconnect",
          "borg.channel.google.getStatus",
          "borg.channel.google.inject"
        ],
        "kinds": [
          "channel",
          "settingsPage",
          "tool"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-channel-google/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.channel.imap",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-channel-imap/main",
      "ui": "@borg/plugin-channel-imap/ui",
      "permissions": [
        "channels.register",
        "network:tls",
        "runtime.background",
        "secrets:read",
        "secrets:write",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.channel.imap.inject"
        ],
        "kinds": [
          "channel",
          "settingsPage"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-channel-imap/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.channel.m365",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-channel-m365/main",
      "ui": "@borg/plugin-channel-m365/ui",
      "permissions": [
        "channels.register",
        "oauth.connect",
        "network:dynamic",
        "runtime.background",
        "tools.register",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.channel.m365.connect",
          "borg.channel.m365.disconnect",
          "borg.channel.m365.getStatus",
          "borg.channel.m365.inject"
        ],
        "kinds": [
          "channel",
          "settingsPage",
          "tool"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-channel-m365/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.channel.mock",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-channel-mock/main",
      "permissions": [
        "channels.register",
        "channels.send"
      ],
      "contributes": {
        "commands": [
          "borg.channel.mock.inject",
          "borg.channel.mock.send"
        ],
        "kinds": [
          "channel"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-channel-mock/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.channel.slack",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-channel-slack/main",
      "ui": "@borg/plugin-channel-slack/ui",
      "permissions": [
        "channels.register",
        "network:dynamic",
        "network:websocket",
        "runtime.background",
        "secrets:read",
        "secrets:write",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.channel.slack.disconnect",
          "borg.channel.slack.getStatus",
          "borg.channel.slack.verify"
        ],
        "kinds": [
          "channel",
          "settingsPage"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-channel-slack/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.chat",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-chat/main",
      "ui": "@borg/plugin-chat/ui",
      "permissions": [
        "executions.manage",
        "loops.start",
        "memory.write",
        "models.read",
        "personas.read",
        "personas.write",
        "tools.invoke",
        "ui.embeddedContent.consume",
        "ui.flightDeck",
        "ui.settings",
        "ui.wizard",
        "ui.workspace",
        "workspace.manage"
      ],
      "contributes": {
        "commands": [
          "borg.chat.append",
          "borg.chat.createSession",
          "borg.chat.deleteSession",
          "borg.chat.getSession",
          "borg.chat.listSessions",
          "borg.chat.listWorkspace",
          "borg.chat.sendMessage",
          "borg.chat.spawnSubAgent"
        ],
        "events": [
          "borg.chat.message.appended",
          "borg.chat.session.deleted",
          "borg.chat.session.updated",
          "borg.chat.turn.completed",
          "borg.chat.turn.started"
        ],
        "kinds": [
          "flightDeckWidget",
          "settingsPage",
          "wizardStep",
          "workspaceView"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-chat/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.coinbase",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-coinbase/main",
      "ui": "@borg/plugin-coinbase/ui",
      "permissions": [
        "network:api.coinbase.com",
        "network:api-sandbox.coinbase.com",
        "network:dynamic",
        "secrets:read",
        "secrets:write",
        "tools.register",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.coinbase.disconnect",
          "borg.coinbase.getStatus",
          "borg.coinbase.verify"
        ],
        "kinds": [
          "settingsPage",
          "tool"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-coinbase/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.config.sqlite",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-config-sqlite/main",
      "permissions": [
        "fs:pluginData"
      ],
      "contributes": {
        "kinds": [
          "configStore"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-config-sqlite/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.context-map",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-context-map/main",
      "permissions": [
        "prompts.register"
      ],
      "contributes": {
        "kinds": [
          "promptSlot"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-context-map/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.copilot",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-copilot/main",
      "ui": "@borg/plugin-copilot/ui",
      "permissions": [
        "models.register",
        "network:api.github.com",
        "network:api.githubcopilot.com",
        "network:github.com",
        "secrets:read",
        "secrets:write",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "commands": [
          "borg.copilot.connect",
          "borg.copilot.disconnect",
          "borg.copilot.getStatus",
          "borg.copilot.pollDeviceFlow",
          "borg.copilot.startDeviceFlow"
        ],
        "kinds": [
          "llmProvider",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-copilot/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.feedback",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-feedback/main",
      "ui": "@borg/plugin-feedback/ui",
      "permissions": [
        "interactions.read",
        "interactions.request:human_input",
        "notifications:send",
        "tools.register",
        "window.show",
        "ui.flightDeck",
        "ui.interactions",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.feedback.ask"
        ],
        "events": [
          "borg.feedback.requested",
          "borg.feedback.resolved"
        ],
        "kinds": [
          "tool",
          "interactionRenderer",
          "flightDeckWidget",
          "settingsPage"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-feedback/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.graphs",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-graphs/main",
      "ui": "@borg/plugin-graphs/ui",
      "permissions": [
        "executions.manage",
        "graphs.readContributions",
        "loops.start",
        "models.complete",
        "personas.read",
        "runtime.background",
        "scheduler.manage",
        "tools.invoke",
        "tools.register",
        "ui.flightDeck",
        "ui.settings",
        "ui.workspace",
        "workspace.manage"
      ],
      "contributes": {
        "commands": [
          "borg.graphs.cancelInstance",
          "borg.graphs.deleteDefinition",
          "borg.graphs.getDefinition",
          "borg.graphs.getInstance",
          "borg.graphs.launch",
          "borg.graphs.listContributions",
          "borg.graphs.listDefinitions",
          "borg.graphs.listInstances",
          "borg.graphs.listRunning",
          "borg.graphs.saveDefinition"
        ],
        "events": [
          "borg.graphs.definition.deleted",
          "borg.graphs.definition.saved",
          "borg.graphs.instance.completed",
          "borg.graphs.instance.failed",
          "borg.graphs.instance.started",
          "borg.graphs.instance.updated",
          "borg.graphs.step.completed"
        ],
        "extensionPoints": [
          "borg.graphs.graphStep",
          "borg.graphs.graphTrigger"
        ],
        "kinds": [
          "flightDeckWidget",
          "graphEngine",
          "settingsPage",
          "tool",
          "workspaceView"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-graphs/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.hello",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-hello/main",
      "ui": "@borg/plugin-hello/ui",
      "permissions": [
        "notifications:send",
        "ui.flightDeck",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.hello.getStatus"
        ],
        "kinds": [
          "flightDeckWidget",
          "settingsPage"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-hello/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.mcp",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-mcp/main",
      "ui": "@borg/plugin-mcp/ui",
      "permissions": [
        "network:dynamic",
        "personas.read",
        "personas.write",
        "secrets:read",
        "subprocess:mcp",
        "tools.provide",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.mcp.getStatus",
          "borg.mcp.listServers",
          "borg.mcp.refresh"
        ],
        "events": [
          "borg.mcp.appDiscovered"
        ],
        "kinds": [
          "settingsPage",
          "toolProvider"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-mcp/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.mcp-apps",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-mcp-apps/main",
      "ui": "@borg/plugin-mcp-apps/ui",
      "permissions": [
        "personas.read",
        "tools.invoke",
        "ui.embeddedContent.render"
      ],
      "contributes": {
        "commands": [
          "borg.mcpApps.cancelTool",
          "borg.mcpApps.invokeTool"
        ],
        "events": [
          "borg.embeddedContent.registered",
          "borg.mcpApps.toolResponded"
        ],
        "kinds": [
          "embeddedContentRenderer"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-mcp-apps/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.memory.knowledge",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-memory-knowledge/main",
      "permissions": [
        "memory.provide"
      ],
      "contributes": {
        "kinds": [
          "memoryProvider"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-memory-knowledge/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.mock-llm",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-mock-llm/main",
      "ui": "@borg/plugin-mock-llm/ui",
      "permissions": [
        "models.register",
        "loops.start",
        "tools.invoke",
        "ui.workspace"
      ],
      "contributes": {
        "kinds": [
          "llmProvider",
          "workspaceView"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-mock-llm/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.ollama",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-ollama/main",
      "ui": "@borg/plugin-ollama/ui",
      "permissions": [
        "models.register",
        "network:dynamic",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "commands": [
          "borg.ollama.connect",
          "borg.ollama.disconnect",
          "borg.ollama.getStatus"
        ],
        "kinds": [
          "llmProvider",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-ollama/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.openai",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-openai/main",
      "ui": "@borg/plugin-openai/ui",
      "permissions": [
        "models.register",
        "network:api.openai.com",
        "secrets:read",
        "secrets:write",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "commands": [
          "borg.openai.connect",
          "borg.openai.disconnect",
          "borg.openai.getStatus"
        ],
        "kinds": [
          "llmProvider",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-openai/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.openrouter",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-openrouter/main",
      "ui": "@borg/plugin-openrouter/ui",
      "permissions": [
        "models.register",
        "network:openrouter.ai",
        "secrets:read",
        "secrets:write",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "commands": [
          "borg.openrouter.connect",
          "borg.openrouter.disconnect",
          "borg.openrouter.getStatus"
        ],
        "kinds": [
          "llmProvider",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-openrouter/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.search.brave",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-search-brave/main",
      "ui": "@borg/plugin-search-brave/ui",
      "permissions": [
        "network:dynamic",
        "secrets:read",
        "secrets:write",
        "tools.register",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.search.brave.connect",
          "borg.search.brave.disconnect",
          "borg.search.brave.getStatus"
        ],
        "kinds": [
          "settingsPage",
          "tool"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-search-brave/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.search.tavily",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-search-tavily/main",
      "ui": "@borg/plugin-search-tavily/ui",
      "permissions": [
        "network:dynamic",
        "secrets:read",
        "secrets:write",
        "tools.register",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.search.tavily.connect",
          "borg.search.tavily.disconnect",
          "borg.search.tavily.getStatus"
        ],
        "kinds": [
          "settingsPage",
          "tool"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-search-tavily/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.secrets.dev",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-secrets-dev/main",
      "ui": "@borg/plugin-secrets-dev/ui",
      "permissions": [
        "fs:pluginData",
        "secrets:read",
        "secrets:write",
        "notifications:send",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "kinds": [
          "secretStore",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-secrets-dev/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.secrets.os",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-secrets-os/main",
      "ui": "@borg/plugin-secrets-os/ui",
      "permissions": [
        "fs:pluginData",
        "secrets:read",
        "secrets:write",
        "notifications:send",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "kinds": [
          "secretStore",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-secrets-os/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.security.prompt-injection",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-security-prompt-injection/main",
      "permissions": [
        "scanners.register"
      ],
      "contributes": {
        "kinds": [
          "promptScanner"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-security-prompt-injection/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.themes",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-themes/main",
      "ui": "@borg/plugin-themes/ui",
      "permissions": [
        "ui.settings"
      ],
      "contributes": {
        "kinds": [
          "settingsPage"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-themes/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.tools.core",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-tools-core/main",
      "permissions": [
        "fs:sessionWorkspace",
        "tools.register",
        "sandbox.run"
      ],
      "contributes": {
        "kinds": [
          "tool"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-tools-core/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.tools.echo",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-tools-echo/main",
      "permissions": [
        "tools.register"
      ],
      "contributes": {
        "kinds": [
          "tool"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-tools-echo/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.usage",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-usage/main",
      "ui": "@borg/plugin-usage/ui",
      "permissions": [
        "cost.read",
        "ui.flightDeck"
      ],
      "contributes": {
        "kinds": [
          "flightDeckWidget"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-usage/main") as { default: PluginDefinition }).default,
  },
];
