// Generated by scripts/generate-bundled-plugins.mjs. Do not edit.
import type { PluginSource } from "@borg/kernel";
import type { PluginDefinition } from "@borg/plugin-sdk";

export const bundledMainPlugins: readonly PluginSource[] = [
  {
    manifest: {
      "id": "borg.config.sqlite",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-config-sqlite/main",
      "permissions": [
        "fs:pluginData"
      ],
      "contributes": {
        "kinds": [
          "configStore"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-config-sqlite/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.feedback",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-feedback/main",
      "ui": "@borg/plugin-feedback/ui",
      "permissions": [
        "interactions.read",
        "interactions.request:human_input",
        "notifications:send",
        "tools.register",
        "window.show",
        "ui.flightDeck",
        "ui.interactions",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.feedback.ask"
        ],
        "events": [
          "borg.feedback.requested",
          "borg.feedback.resolved"
        ],
        "kinds": [
          "tool",
          "interactionRenderer",
          "flightDeckWidget",
          "settingsPage"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-feedback/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.hello",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-hello/main",
      "ui": "@borg/plugin-hello/ui",
      "permissions": [
        "notifications:send",
        "ui.flightDeck",
        "ui.settings"
      ],
      "contributes": {
        "commands": [
          "borg.hello.getStatus"
        ],
        "kinds": [
          "flightDeckWidget",
          "settingsPage"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-hello/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.mock-llm",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-mock-llm/main",
      "ui": "@borg/plugin-mock-llm/ui",
      "permissions": [
        "models.register",
        "loops.start",
        "tools.invoke",
        "ui.workspace"
      ],
      "contributes": {
        "kinds": [
          "llmProvider",
          "workspaceView"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-mock-llm/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.secrets.dev",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-secrets-dev/main",
      "ui": "@borg/plugin-secrets-dev/ui",
      "permissions": [
        "fs:pluginData",
        "secrets:read",
        "secrets:write",
        "notifications:send",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "kinds": [
          "secretStore",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-secrets-dev/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.secrets.os",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-secrets-os/main",
      "ui": "@borg/plugin-secrets-os/ui",
      "permissions": [
        "fs:pluginData",
        "secrets:read",
        "secrets:write",
        "notifications:send",
        "ui.settings",
        "ui.wizard"
      ],
      "contributes": {
        "kinds": [
          "secretStore",
          "settingsPage",
          "wizardStep"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-secrets-os/main") as { default: PluginDefinition }).default,
  },
  {
    manifest: {
      "id": "borg.tools.echo",
      "version": "0.1.0",
      "engines": {
        "borg": "^0.1.0"
      },
      "main": "@borg/plugin-tools-echo/main",
      "permissions": [
        "tools.register"
      ],
      "contributes": {
        "kinds": [
          "tool"
        ]
      }
    },
    loadMain: async () =>
      (require("@borg/plugin-tools-echo/main") as { default: PluginDefinition }).default,
  },
];
